[build]
default-target = "x86_64-unknown-linux-gnu"
[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install gcc libc-dev:$CROSS_DEB_ARCH libudev-dev:$CROSS_DEB_ARCH pkg-config libssl-dev:$CROSS_DEB_ARCH openssl:$CROSS_DEB_ARCH"
]